# Generated by Django 6.0.5 on 2026-05-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('F', 'Food'), ('D', 'Drink'), ('O', 'Other')], max_length=30)),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
    ]
